-- Create the polls table
CREATE TABLE polls (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  question TEXT NOT NULL,
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Create the poll_options table
CREATE TABLE poll_options (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  text TEXT NOT NULL,
  poll_id UUID REFERENCES polls(id) ON DELETE CASCADE
);

-- Create the votes table
CREATE TABLE votes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  option_id UUID REFERENCES poll_options(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id),
  poll_id UUID REFERENCES polls(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now()
);
